table DateCalendar
	lineageTag: 34a3358c-a7c2-4999-8486-732424ca8e3c

	column PK_Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3143aca4-71e3-4863-b26c-428ac615872d
		summarizeBy: none
		sourceColumn: PK_Date

		variation Variation
			isDefault
			relationship: 5f906fb8-edf9-46bc-b25a-7f9b8ee4e99a
			defaultHierarchy: LocalDateTable_ab442b9d-cd5d-49a4-aa9c-34b5b48e6b14.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 8cec3e22-7ca0-491f-9a1c-2ae5d1a85e18
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column QuarterofYear
		dataType: int64
		formatString: 0
		lineageTag: 46ea4762-54d2-45cf-82c3-ebd1fd4a750c
		summarizeBy: sum
		sourceColumn: QuarterofYear

		annotation SummarizationSetBy = Automatic

	column QuarterNameOfYear
		dataType: string
		lineageTag: ee735680-1173-4763-bd2d-ce0479db7d34
		summarizeBy: none
		sourceColumn: QuarterNameOfYear

		annotation SummarizationSetBy = Automatic

	column QuarterWithYear
		dataType: string
		lineageTag: de91d270-7d1d-4e19-8952-10d2dcd8245d
		summarizeBy: none
		sourceColumn: QuarterWithYear

		annotation SummarizationSetBy = Automatic

	column MonthNum
		dataType: int64
		formatString: 0
		lineageTag: b6e3725e-8a1d-45fa-90da-967f9583ab19
		summarizeBy: sum
		sourceColumn: MonthNum

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 04e37c78-8872-451b-a2ea-ade49d36faa1
		summarizeBy: none
		sourceColumn: MonthName

		annotation SummarizationSetBy = Automatic

	column MonthNameShort
		dataType: string
		lineageTag: d4140bf0-7c40-48e4-b3de-c2be69bf699a
		summarizeBy: none
		sourceColumn: MonthNameShort

		annotation SummarizationSetBy = Automatic

	column MonthWithYear
		dataType: string
		lineageTag: dc45ffad-72db-4d63-8a1d-291685245c7d
		summarizeBy: none
		sourceColumn: MonthWithYear

		annotation SummarizationSetBy = Automatic

	column MonthNameSorting
		dataType: int64
		formatString: 0
		lineageTag: 0547ba0e-0949-40b8-8664-5d88d453f161
		summarizeBy: sum
		sourceColumn: MonthNameSorting

		annotation SummarizationSetBy = Automatic

	column WeekNumOfYear
		dataType: int64
		formatString: 0
		lineageTag: 47d32574-5755-462f-b383-86843493551a
		summarizeBy: sum
		sourceColumn: WeekNumOfYear

		annotation SummarizationSetBy = Automatic

	column WeekNameOfYear
		dataType: string
		lineageTag: 19a5d260-36f9-4c31-a60f-e0cafe10772b
		summarizeBy: none
		sourceColumn: WeekNameOfYear

		annotation SummarizationSetBy = Automatic

	column WeekWithYear
		dataType: string
		lineageTag: 82a3c81a-31e7-4b06-80ab-efc60bc68b5d
		summarizeBy: none
		sourceColumn: WeekWithYear

		annotation SummarizationSetBy = Automatic

	column DayNumOfWeek
		dataType: int64
		formatString: 0
		lineageTag: 928b6dda-2fc9-47e6-985d-45c10a588c88
		summarizeBy: sum
		sourceColumn: DayNumOfWeek

		annotation SummarizationSetBy = Automatic

	column DayNameofWeek
		dataType: string
		lineageTag: bcf9b23e-3151-47a4-af83-a63da781c38c
		summarizeBy: none
		sourceColumn: DayNameofWeek

		annotation SummarizationSetBy = Automatic

	partition DateCalendar = m
		mode: import
		source =
				let
				    StartDate = #date(2025,1,1),
				    EndDate = #date(2026, 1, 1),
				    DateList = List.Dates(StartDate, Number.From(EndDate) - Number.From(StartDate), #duration(1, 0, 0, 0)),
				    DatesAsTable = Table.FromList(DateList, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    RenamedColumnDate = Table.RenameColumns(DatesAsTable, {{"Column1", "PK_Date"}}),
				    ChangedTypeDate = Table.TransformColumnTypes(RenamedColumnDate,{{"PK_Date", type date}}),
				    Year = Table.AddColumn(ChangedTypeDate, "Year", each Date.Year([PK_Date])),
				    QuarterOfYear = Table.AddColumn(Year, "QuarterofYear", each Date.QuarterOfYear([PK_Date])),
				    QuarterNameOfYear = Table.AddColumn(QuarterOfYear, "QuarterNameOfYear", each "Q" & Number.ToText([QuarterofYear])),
				    QuarterWithYear = Table.AddColumn(QuarterNameOfYear, "QuarterWithYear", each Number.ToText([Year]) & "-" & [QuarterNameOfYear]),
				    MonthNum = Table.AddColumn(QuarterWithYear, "MonthNum", each Date.Month([PK_Date])),
				    MonthName = Table.AddColumn(MonthNum, "MonthName", each Date.ToText([PK_Date], "MMMM")),
				    MonthNameShort = Table.AddColumn(MonthName, "MonthNameShort", each Date.ToText([PK_Date], "MMM")),
				    MonthWIthYear = Table.AddColumn(MonthNameShort, "MonthWithYear", each Number.ToText([Year]) & "-" & [MonthNameShort]),
				    MonthNameSorting = Table.AddColumn(MonthWIthYear, "MonthNameSorting", each [Year] * 10 + [MonthNum]),
				    WeekNumOfYear = Table.AddColumn(MonthNameSorting, "WeekNumOfYear", each Date.WeekOfYear([PK_Date])),
				    WeekNameOfYear = Table.AddColumn(WeekNumOfYear, "WeekNameOfYear", each "KW" & Text.PadStart(Number.ToText([WeekNumOfYear]),2,"0")),
				    WeekWithYear = Table.AddColumn(WeekNameOfYear, "WeekWithYear", each Number.ToText([Year]) & "-" & [WeekNameOfYear]),
				    DayNumOfYear = Table.AddColumn(WeekWithYear, "DayNumOfWeek", each Date.DayOfWeek([PK_Date])+1),
				    DayNameOfWeek = Table.AddColumn(DayNumOfYear, "DayNameofWeek", each Text.Start(Date.DayOfWeekName([PK_Date]), 3)),
				    ChangeType = Table.TransformColumnTypes(DayNameOfWeek,{{"Year", Int64.Type}, {"QuarterofYear", Int64.Type}, {"MonthNum", Int64.Type}, {"WeekNumOfYear", Int64.Type}, {"QuarterNameOfYear", type text}, {"QuarterWithYear", type text}, {"MonthName", type text}, {"MonthNameShort", type text}, {"MonthWithYear", type text}, {"WeekNameOfYear", type text}, {"DayNameofWeek", type text}, {"DayNumOfWeek", Int64.Type}, {"MonthNameSorting", Int64.Type}})
				in
				    ChangeType

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

