/// One row per SubCategory, mapping transactions to financial type, category, and allocation. Savings and investment contributions currently map to Expense.
table TransactionCategory_dim
	lineageTag: c5cf7f0c-1389-4be0-800b-01561ed10fff

	/// Classification used by income and expense measures. Asset entries include cash transfers and credit card payments.
	column 'Financial Type'
		dataType: string
		isHidden
		lineageTag: d16568b9-6373-4b9a-aa6f-430c2332dafe
		summarizeBy: none
		sourceColumn: Financial Type

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Broad category for grouping transaction subcategories.
	column Category
		dataType: string
		isHidden
		lineageTag: 25b23d3a-07e1-47ee-9c0d-4658d871048b
		summarizeBy: none
		sourceColumn: Category

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Unique mapping key matching transaction SubCategory values.
	column SubCategory
		dataType: string
		isHidden
		lineageTag: 352da5c6-3385-43e1-8409-771b001cd4ef
		summarizeBy: none
		sourceColumn: SubCategory

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Allocation group used for Needs, Wants, and Investments shares; other values describe income, transfers, or payments.
	column 'Allocation Type'
		dataType: string
		lineageTag: 0aae4f54-c381-49f9-b55c-4a7d6f5dabf0
		summarizeBy: none
		sourceColumn: Allocation Type

		annotation SummarizationSetBy = Automatic

	hierarchy CategoryHierarchy
		lineageTag: 8fb94777-16e5-4d5d-a60e-3f10965370b2

		level 'Financial Type'
			lineageTag: 157d99be-b20a-475f-a87e-438f6542f1fc
			column: 'Financial Type'

		level Category
			lineageTag: bfc36a9e-7d2b-46d6-80bd-bf01dad39222
			column: Category

		level SubCategory
			lineageTag: 91afa0f7-edaa-4222-bd51-f2ba99957495
			column: SubCategory

	partition TransactionCategory_dim = m
		mode: import
		source =
				let
					Source = Excel.Workbook(File.Contents(TransactionDataFolder & "\\Transaction Category.xlsx"), null, true),
					Table1_Table = Source{[Item="Table1", Kind="Table"]}[Data],
					#"Changed Type" = Table.TransformColumnTypes(
						Table1_Table,
						{
							{"Financial Type", type text},
							{"Category", type text},
							{"SubCategory", type text},
							{"Allocation Type", type text}
						}
					)
				in
					#"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

